### PR TITLE
Add support for Bzlmod

### PR DESCRIPTION
**Pull request by fmeum**
Publishing to the Bazel Central Registry (https://registry.bazel.build) can be added as a follow-up PR.

### CODE REVIEW

**Comment by fmeum** [comment]
@johnynek Let me know if you would want me to provide more context on Bzlmod and the BCR.

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by fmeum** [comment]
@eed3si9n Would you accept a follow-up PR that adds the configuration required for automating releases to the Bazel Central Registry? If you don't want that just yet, you could also create a regular release and I could manually it to the BCR.

**Comment by eed3si9n** [comment]
@fmeum Automation sounds awesome.

**Pull request merged**
